apiVersion: apps/v1
kind: Deployment
metadata: 
     name: mavenproject
     labels: 
        app: webapp 
spec:
     replicas: 1
     selector:
        matchLabels:
           app: webapp
     template:
        metadata:
           labels:
              app: webapp
        spec:
           containers:
            - name: tomcat
              image: kiran5108/tomcat:cf4a48cf313452a49bc8c12175da2feb7f6034ad
              ports:
              - containerPort: 8080                 
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
    
spec:
  type: NodePort
  selector: 
      app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31080